//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vehicle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreatorIP { get; set; }
        public string CreatorRole { get; set; }
        public string UpdaterIP { get; set; }
        public string UpdaterRole { get; set; }
    }
}
